# 'ITEM_A'(PARENT 아이템 ID)->'ITEM_B'(자식)와 같이 업그레이드 가능 / PARENT 아이템X = ROOT 아이템
# SELECT ITEM_ID,	ITEM_NAME,	RARITY,	PRICE FROM ITEM_INFO
# SELECT ITEM_ID, PARENT_ITEM_ID FROM ITEM_TREE

SELECT a.ITEM_ID, a.ITEM_NAME 
    FROM ITEM_INFO a INNER JOIN ITEM_TREE b ON a.ITEM_ID = b.ITEM_ID
    WHERE b.PARENT_ITEM_ID IS NULL
    ORDER BY b.ITEM_ID ASC